export const paymentConfig = {
  companyName: 'Kriyon Group Pvt. Ltd.',
  companyNameFull: 'Kriyon Group Pvt. Ltd.',
  upi: {
    id: 'kriyon@ptyes',
    name: 'Kriyon Group Pvt. Ltd.',
  },
  bank: {
    bankName: 'HDFC Bank',
    accountHolder: 'Kriyon Group Pvt. Ltd.',
    accountNumber: '50200098333737',
    accountNumberMasked: '50200098333737',
    ifsc: 'HDFC0000241',
    branchName: undefined,
  },
  contact: {
    phone: '+91 96221 21100',
    email: 'support@repixelx.tech',
    whatsapp: '919622121100',
  },
  qrCode: '/kriyon-qr.png',
}

export const kriyonConfig = {
  companyName: 'Kriyon Group Pvt. Ltd.',
  tagline: 'Building AI-first products and digital systems',
  positioning: 'Kriyon builds systems, not just products.',
  founded: '2023',
  description: 'Kriyon Group Pvt. Ltd. is a future-driven ecosystem solving global challenges through technology, space innovation, and hardware intelligence. We are a global ecosystem driving innovation in AI, design, and technology to shape the future. Every venture we build pushes boundaries and redefines industries.',
  vision: "To solve the world's toughest problems with technology, space innovation, and hardware intelligence.",
  website: 'www.kriyongroup.com',
  email: 'kriyon@repixelx.tech',
  phone: '+91 96221 21100',
  whatsapp: '919622121100',
  highlights: [
    'AI-First',
    'Scalable Systems',
    'Modern UI',
    'Trusted Ventures',
  ],
  social: {
    linkedin: 'https://linkedin.com/company/kriyon-group',
    instagram: 'https://instagram.com/kriyongroup',
  },
  ventures: [
    {
      name: 'RepixelX Studio',
      founded: '2024',
      tagline: 'We Repixelx Your Pixelated Brand.',
      description: 'RepixelX Studio is a studio driven by design, innovation, and performance. We blend creativity, code, and strategy to craft brands that rise above the noise and deliver real results. From web development to branding and growth strategy — we help businesses scale with impact.',
      vision: 'To transform ideas into impactful solutions for brands ready to stand out.',
      website: 'www.repixelx.com',
      email: 'hello@repixelx.com',
      logo: '/logos/dc.png',
    },
    {
      name: 'Edova',
      founded: '2025',
      tagline: "India's 1st GenAI Exam Engine.",
      description: "Edova is India's 1st GenAI Exam Engine, creating fresh exam-level questions, AI explanations, custom mock tests and instant video lectures in seconds. Built to replace outdated coaching with faster, smarter, AI-first learning — the platform every coaching will fear, and every student will trust.",
      vision: 'To revolutionize education with AI-first learning that replaces traditional coaching.',
      website: 'edova.in',
      email: 'edova@repixelx.tech',
      logo: '/logos/edova logo.png',
    },
    {
      name: 'OneLink',
      founded: '2024',
      tagline: 'Stop Sharing Everything. Share OneLink.',
      description: 'OneLink replaces scattered links, QR codes, and profiles with one smart business page. Enable calls, WhatsApp messages, UPI payments, services, location, and brand presence — all accessible instantly through a single shareable link.',
      vision: 'To simplify business communication with one powerful link.',
      website: 'repixelx.com/onelink',
      email: 'hello@repixelx.tech',
      logo: '/logos/Frame 8461.png',
    },
  ],
  coreFocus: ['AI', 'Design', 'Development', 'Platforms'],
  operatingModel: 'Digital-first • Product-led • Scalable systems',
  location: 'India',
  about: {
    title: 'About Kriyon Group',
    shortDescription: 'Kriyon Group Pvt. Ltd. is a future-driven ecosystem solving global challenges through technology, space innovation, and hardware intelligence.',
    fullDescription: 'Kriyon Group Pvt. Ltd. is a future-driven ecosystem solving global challenges through technology, space innovation, and hardware intelligence. We are a global ecosystem driving innovation in AI, design, and technology to shape the future. Every venture we build pushes boundaries and redefines industries.\n\nOur vision is to solve the world\'s toughest problems with technology, space innovation, and hardware intelligence. We build systems, not just products.',
  },
}
